---
title: "README"
author: "Amy Stringer"
date: "27/05/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Purpose 

The purpose of this application is for it to act as a teaching tool for Year 12 High School teachers following recent changes to the Australian Curriculum. The design is not to replace any of the teacher's roles, but rather complement the teacher's explanations of topics. For this reason, the application mostly consists of visual demonstrations.

# Where is it Deployed? 

This app is deployed on the QUT School of Maths shinyapps.io site, linked [here](https://qutschoolofmaths.shinyapps.io/specialistmaths/).

# The Curriculum {.tabset}

## Topic 1 - Integration and Applications of Integration 

### Integration Techniques 

- Integrate using the trigonometric identities $\sin^2 x = \frac{1}{2}(1 - \cos(2x)), \, \cos^2x = \frac{1}{2}(1+ \cos(2x))$ and $1+\tan^2 x = \sec^2x$ (ACMSM116)
- Use substitution $u = g(x)$ to integrate expression of the form $f(g(x))g'(x)$ (ACMSM117)
- Establish and use the formula $\int \frac{1}{x}dx = \ln |x| + c$ for $x \neq 0$ (ACMSM118)
- Find and use the inverse trigonometric functions: arcsine, arccosine and arctangent (ARCSM119)
- Find and use the derivative of the inverse trigonometric functions: arcsine, arccosine and arctangent (ACMSM120)
- Integrate expressions of the form $\frac{\pm 1}{\sqrt{a^2 - x^2}}$ and $\frac{a}{a^2 + x^2}$ (ACMSM121)
- Use partial fractions where necessary for integration in simple cases (ACMSM122)
- Integrate by parts (ACMSM123)

### Applications of Integral Calculus 

- Calculate areas between curves determined by functions (ACMSM124)
- Determine volumes of solids of revolution about either axis (ACMSM125)
- Use numerical integration using technology $f(t) = \lambda e^{-\lambda t}$ for $t \geq 0$ of the exponential random variable with parameter $\lambda > 0$, and use the exponential random variables and associated probabilities and quantities to model data and solve practical problems (ACMSM127)
- Use numerical integration using technology (ACMSM126)

## Topic 2 - Rates of Change and Differential Equations 

- Use implicit differentiation to determine the gradient of curves whose equations are give in implicit form (ACMSM128)
- Related rates as instances of the chain rule: $\frac{dy}{dx} = \frac{dy}{du}\times \frac{du}{dx}$ (ACMSM129)
- Solve simple first-order differential equations of the form $\frac{dy}{dx}= f(x)$, differential equations of the form $\frac{dy}{dx} = g(y)$ and, in general, differential equations of the form $\frac{dy}{dx} = f(x)g(y)$ using separation of variables (ACMSM130)
- Examine slope (direction or gradient) fields of a first order differential equation (ACMSM131)
- Formulate differential equations including the logistic equation that will arise in, for example, chemistry, biology and economics, in situations where rates are involved. (ACMSM132)

### Modelling Motion

- Examine momentum, force, resultant force, action and reaction (ACMSM133)
- Consider constant and non-constant force (ACMSM134)
- Understand motion of a body under concurrent forces (ACMSM135)
- Consider and solve problems involving motion in a straight line with both constant and non-constant acceleration, including simple harmonic motion and the use of expressions $\frac{dv}{dt}, \, v\frac{dv}{dx}$ and $\frac{d(\frac{1}{2}v^2)}{dx}$ for acceleration. (ACMSM136)

## Topic 3 - Statistical Inference 

### Sample Means 

- Examine the concept of the sample mean $X$ as a random variable whose value varies between samples where $X$ is a random variable with mean $\mu$ and the standard deviation $\sigma$ (ACMSM137)
- Simulate repeated random sampling, from a variety of distributions and a range of sample sizes, to illustrate properties of the distribution of $\bar{X}$ across samples of a fixed size $n$ including its mean $\mu$, its standard deviation $\sigma/\sqrt{n}$ (where $\mu$ and $\sigma$ are the mean and standard deviation of $X$) and its approximate normality if $n$ is large (ACMSM138)
- Simulate repeated random sampling, from a variety of distributions and a range of sample sizes, to illustrate the approximate normality of $\frac{\bar{X}-\mu}{s/\sqrt{n}}$ for large samples $(n \geq 30)$ where $s$ is the sample standard deviation  (ACMSM139) 

### Confidence Intervals for Means 

- Understand the concept of an interval estimate for a parameter associated with a random variable (ACMSM140)
- Examine the approximate confidence interval $\left( \bar{X}-\frac{zs}{\sqrt{n}}, \bar{X}+\frac{zs}{\sqrt{n}} \right)$, as an interval estimate for $\mu$, the population mean, where $z$ is the appropriate quantile for the standard normal distribution (ACMSM141)
- Use simulation to illustrate variations in confidence intervals between samples and to show that most but not all confidence intervals contain $\mu$ (ACMSM142)
- Use $\bar{x}$ and $s$ to estimate $\mu$ and $\sigma$, to obtain approximate intervals covering desired proportions of values of a normal random variable and compare with an approximate confidence interval for $\mu$ (ACMSM143)
- Collect data and construct an approximate confidence interval to estimate a mean and to report on survey procedures and data quality. (ACMSM144)

# App Features {.tabset}

Please note that this app primarily focuses on the statistical components of the curriculum detailed above. The reason for this is that the calculus topics are primarily focused on techniques, rather than the concept of a derivative or integral. These techniques need to be done using pen and paper and there are no obvious visualisation that could be used to assist in the teaching or learning of these techniques. 

## Welcome Tab 

In this tab we introduce the app, the topics contained in the app and also present a glossary of terms likely to be used throughout the app. 

## Tab 1 - Sampling Means 

The purpose of this tab is to demonstrate that the sample mean is generally approximately the same across multiple samples, regardless of the distribution which was sampled from. Users are given the opportunity to select a distribution to sample from. The program then simulates 9 sets of 250 samples and plots the distribution of values for each of the simulations. The program also computes the mean value for each simulation, and displays these in a table in the main panel. 

What we want users to see by doing this is that not even simulation looks exactly the same, despite the data being simulated from the same distribution and also that the sample mean for each simulation is generally similar regardless of the distribution from which the samples were taken. 

## Tab 2 - Repeated Sampling 

The next tab is a demonstration of the central limit theorem. This tab was designed to be interactive, but due to issues in deployment, this feature has been removed and now the tab is purely demonstrative. It contains two rows of plots; the first row presents the PDF/PMF of a chosen distribution, and the second row presents a .gif illustrating the distribution of sample means of data simulated according to the above distribution for varying numbers of samples (n = 25 to n = 100 to n = 250). Ideally, students will be able to see that as the number of samples is increased in the simulation process, the distribution of sample means becomes more and more normal. 

### Details 

The data for the .gif file was generated as follows: 
For each distribution type:

1. Generate three sets of 200 simulated datasets, with values simulated according to the relevant distribution
    a. The first set will have only 25 samples per simulation 
    b. The second set will have 100 samples per simulation
    c. The third set will have 250 samples per simulation 
2. Compute the mean value for each simulation for each set of simulations
3. Plot a histogram of the sample means for each set and use the number of samples as the transition states. We could have used `facet_wrap()` here but the animation is more fun and keeps things nice and square for the grid format. 

Code for the production of the animations is given in the `animations.R` file in this folder. 

### Why not use `renderImage()` for the animations?

In the first trial of this app, all of the code inside `animations.R` was included within the course code for the applications and the animation output was called using `renderImage()`. This was a good trial so long as the app was running on my local machine, however when deployed to shinyapps.io the animations never appeared. Therefore, a fix was produced which meant the .gif files would be generated outside of the app, saved into the www directory and read into the application using `img`. If there is a better way to do this, that allows for a level of interactivity in this tab, be my guest. 

## Tab 3 - Confidence Intervals for Means 

This tab was heavily based on a visualisation by [Kristoffer Magnusson](https://rpsychologist.com/d3/ci/), modified to include things relevant to high school students, and also to be programmed into R. I originally found this on the [Seeing Theory](https://seeing-theory.brown.edu/frequentist-inference/index.html) website which is cited on the first welcome page within the application. 

This tab has three possible inputs and four corresponding outputs. The inputs allow the user to select a confidence level of interest, and then they may simulate either 10 sample, or 100, and the number of sample accumulates the more the buttons are pressed. 

The outputs then show results from these simulations in a few different ways. Details of what the program does in order to produce these is given below: 

1. Depending on which button is pressed, the program will simulate either 10 and 100 sets of normal data, taken from the standard normal, taking 100 samples per set. 
2. Next the program computes all the necessary statistics for producing confidence intervals. This involves:
    a. grouping the data by simulation 
    b. calculating the mean, standard deviation and number of obs per simulation, as well as the alpha value based on the selected confidence level. 
    c. Next it computes the t values for this alpha value for both lower and upper 
    d. Then it substitutes everything from above into the confidence interval formula. 
3. We wanted some way to distinguish between intervals that contained the true mean and those that didn't. This was computed using a logical formula and used to colour the bars in the final plot 
4. This data is then joined with any previous data computed for the same confidence level choice 
5. In this same step, the data for the pie chart is also computed. This is done by taking the joined dataset we just created, grouping it by the logical variable `inside` and counting up the observations that fall into each group (inside or outside)

Once the data is generated, there are four outputs. The first is the pie chart which visually displays the proportion of intervals which contain the true mean. The second is a text output that displays the numerical proportions because R is not built for pie charts, and getting the text to display in the correct position on the chart is non-trivial. The third output is a plot displaying a red dashed line at the confidence level, and the program plots the actual proportion of intervals containing the true mean as a function of simulation number, illustrating that as we increase the number of simulations, we get closer and closer to, for example, 95% of simulations containing the mean for a confidence level of 95%. The fourth, and final, output on this tab is the main event. Here students will be able to see and interact with the confidence intervals. As more simulations are added to the dataset (via the buttons) more intervals are added to the main panel plot. Not only does the plot contain a red dashed vertical line at the true mean value, it colours the intervals according to whether or not they contain this value.

# The Code {.tabset}

## Tab 1 - Sampling Means 

### Inputs 

- `T3Dist1` (selectInput) - Select one of 6 common distributions (normal, uniform, poisson, binomial, exponential, gamma)

### Outputs 

- `T3SimsPlot1` (plotlyOutput) - Plots a faceted histogram of the data simulated according to the distribution selected by `input$T3Dist1`. 
- `T3means` (dataTableOutput) - This is a table containing the mean value for each of the 9 simulations. Computed using `group_by()` and `summarise()` 

## Tab 2 - Repeated Sampling 

### Inputs 

There are no inputs in this tab, only outputs. 

### Outputs 

- `NormalPDF` (plotOutput) - This is the probability distribution function of a normal distribution with a mean of 169 and a standard deviation of 10. These parameters are arbitrary, the idea was a rough height distribution. 
- `BinomPMF` (plotOutput) - This is the probability mass function of a binomial distribution with a size parameter of 15 and a probability of 0.7. These were chosen arbitrarily to give a nice curve. 
- `UnifPDF` (plotOutput) - This is the probability density function for a uniform distribution with a min of 0 and a max of 4, chosen arbitrarily.  

### Other details 
 
In this tab there are three other plots that are not technically outputs of the shiny app but that require mention. All of these files should be contained in the www folder within this application directory and the code used to produce these images is contained within the `animations.R` file.

- `NormalOutfile.gif` - read into the app using `img()` this file contains an animation of the distribution of sample means for simulations of varying samples sizes, simulated from the normal distribution 
- `BinomialOutfile.gif` - read into the app using `img()` this file contains an animation of the distribution of sample means for simulations of varying samples sizes, simulated from the binomial distribution 
- `UniformOutfile.gif` - read into the app using `img()` this file contains an animation of the distribution of sample means for simulations of varying samples sizes, simulated from the uniform distribution 

## Tab 3 - Confidence Intervals for Means 

### Inputs 

- `confLevel` (sliderInput) - This slider allows the user to select a confidence level to investigate 
- `Add10` (actionButton) - This button allows the user to a further 10 simulations into the fix, which in turn adds another 10 bars to the confidence interval plot in the main panel. 
- `Add100` (actionButton) - This is the same as `Add10` but it adds 100 new simulations, rather than 10. 

### Outputs 

- `ConfIntPie` (plotOutput) - This is a pie chart of the `inside` variable. This is a logical variable indicate TRUE if the true mean is contained within the confidence interval and false otherwise. 
- `ratio` (textOutput) - This is some text to accompany the pie chart. The text gives numerical proportions that match to the segments in the pie chart. 
- `PlotProp` (plotlyOutput) - This plot shows the proportion of intervals containing the true mean as a function of the number of simulations. Also shown here is a dashed red line at the selected confidence level. 
- `PlotIntervals` (plotlyOutput) - This is the main plot in this tab. Like the others it updates each time a button is pressed, but the change in this plot is perhaps for visible than in the others. At the push of the buttons either 10 or 100 more simulations are adding, each contributing to a bar interval on this plot. Bar intervals are coloured according to their containment of the true mean, and the true mean is also plotted as a red dashed vertical line on the plot. 